# Generated by Django 2.1.5 on 2019-02-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('openening_time', models.TimeField(auto_now_add=True)),
                ('closing_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
