# Generated by Django 2.1.5 on 2019-02-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20190211_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='closing_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='openening_time',
            field=models.DateTimeField(),
        ),
    ]
